### ISSUE TITLE
FsJson.jval truncates milliseconds when parsing DateTime values

### ISSUE THREAD

**Issue by ScottShingler** [FsStorm/FsStorm#10]
The current implementation of jval includes the following:

```
let rec jval (o:obj) =
    let safeFloat f = sprintf "%f" f |> float
    match o with
    ...
    | :? DateTime as d      -> JsonString (d.ToString("s"))
```

This is using the sortable date format, which truncates the milliseconds.

To preserve milliseconds, the round-trip format could be used as follows:

```
    | :? DateTime as d      -> JsonString (d.ToString("o"))
```

However, this will also output the timezone offset.  For example, `2015-08-28T10:28:48.8240937-04:00`.  It might be cleaner to specify UTC:

```
    | :? DateTime as d      -> JsonString (DateTime.SpecifyKind(d, DateTimeKind.Utc).ToString("o"))
```

This would output `2015-08-28T10:28:48.8240937Z`.

**Comment by et1975** [comment]
fix released in 0.0.5
