### ISSUE TITLE
Add a link to fsstorm.github.io/FsStorm/ in description line of github.com/FsStorm/FsStorm/

### ISSUE THREAD

**Issue by dsyme** [FsStorm/FsStorm#7]
Please add a link to http://fsstorm.github.io/FsStorm/ in description line of http://github.com/FsStorm/FsStorm/

This makes it much easier to find the docs

thanks!
don

p.s. if you'd like to make me a backup site maintainer to do this sort of cosmetic thing please feel free to do so 

p.p.s. am wondering whether you might join forces with https://github.com/fslaborg.

**Comment by et1975** [comment]
Thanks Don, any improvements to FsStorm you can suggest are always welcome!

**Comment by et1975** [comment]
p.p.s. sure, what can I do for FsLab?
